blueprints/front/forms.py
from wtforms import Form, ValidationError
from wtforms.fields import StringField, IntegerField, FileField
from wtforms.validators import Email, Length, EqualTo, InputRequired
from flask_wtf.file import FileAllowed, FileSize
from models.auth import UserModel
from exts import cache
from flask import request

class BaseForm(Form):
    @property
    def messages(self):
        message_list =[]
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors)
        return message_list

class RegisterForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱")])
    email_captcha = StringField(validators=[Length(6, 6, message="请输入正确的邮箱验证码")])
    username = StringField(validators=[Length(3, 20, message="请输入正确长度的用户名")])
    password = StringField(validators=[Length(6, 20, message="请输入正确长度的密码")])
    repeat_password = StringField(validators=[EqualTo("password", message="两次密码不一致")])
    graph_captcha = StringField(validators=[Length(4, 4, message="请输入正确长度的验证码")])

    def validate_email(self, field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise ValidationError(message="邮箱已经被注册")

    def validate_email_captcha(self, field):
        email_captcha = field.data
        email = self.email.data
        cache_captcha = cache.get(email)
        if not cache_captcha or email_captcha != cache_captcha:
            raise ValidationError(message="邮箱验证码错误")

    def validate_graph_captcha(self, field):
        key = request.cookies.get("_graph_captcha_key")
        cache_captcha = cache.get(key)
        graph_captcha = field.data
        if not cache_captcha or cache_captcha.lower() != graph_captcha.lower():
            raise ValidationError(message="图形验证码错误")


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱")])
    password = StringField(validators=[Length(6, 20, message="请输入正确长度的密码")])
    remember = IntegerField()


class UploadImageForm(BaseForm):
    image = FileField(validators=[FileAllowed(['jpg', 'jpeg', 'png'], message="图片不符合要求！"), FileSize(max_size=1024*1024*5, message="图片最大不能超过5M！")])


class EditProfileForm(BaseForm):
    signature = StringField(validators=[Length(1, 50, message="个性签名在1-50字之间！")])


class PublicPostForm(BaseForm):
    title = StringField(validators=[Length(3,200,message="帖子标题必须在3-200之间")])
    content = StringField(validators=[InputRequired(message="请传入内容！")])
    board_id = IntegerField(validators=[InputRequired(message="请传入模板IO！")])

class PublicCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message="请传入内容！")])
    post_id = IntegerField(validators=[InputRequired(message="请传入帖子ID")])

blueprints/front/__init__.py
from .views import bp as front_bp

blueprints/front/views.py
import string
import random
from flask import (
    Blueprint,
    request,
    render_template,
    jsonify,
    current_app,
    make_response,
    session,
    redirect,
    g,
    url_for
)
from exts import cache, db
from utils import restful
from .forms import RegisterForm, LoginForm, UploadImageForm, EditProfileForm, PublicPostForm, PublicCommentForm
from models.auth import UserModel, Permission
from utils.captcha import Captcha
import time, os
from io import BytesIO
from .decorators import login_required
from hashlib import md5
from flask_avatars import Identicon
from models.post import BoardModel, PostModel, CommentModel, BannerModel
from flask_paginate import get_page_parameter, Pagination
from sqlalchemy.sql import func
from flask_jwt_extended import create_access_token

bp = Blueprint("front", __name__, url_prefix='/')

#写在这个蓝图，这个蓝图中所有的视图函数都可以获取user
# 钩子函数，在调用视图函数之前执行
@bp.before_request
def front_before_request():
    if 'user_id' in session:
        user_id = session.get("user_id")
        user = UserModel.query.get(user_id)
        setattr(g, "user", user)


# 上下文处理器，
@bp.context_processor
def front_context_processor():
    if hasattr(g, "user"):
        return {"user": g.user}
    else:
        return {}


@bp.route('/')
def index():
    sort = request.args.get("st", type=int, default=1)
    board_id = request.args.get("bd", type=int, default=None)
    boards = BoardModel.query.order_by(BoardModel.priority.desc()).all()
    post_query = None
    if sort == 1:
        #最新，按照时间排序
        post_query = PostModel.query.order_by(PostModel.create_time.desc())
    else:
        #按照评论数量进行排序，同等数量下更新的优先
        post_query = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    #总共有多少个帖子
    total = post_query.count()

    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page-1)*current_app.config['PER_PAGE_COUNT']
    end = start + current_app.config['PER_PAGE_COUNT']

    if board_id:
        # "mapped class CommentModel->comment" has no property "board_id"
        # CommentModel中寻找board_id，然后进行过滤
        # post_query = post_query.filter_by(board_id=board_id)
        post_query = post_query.filter(PostModel.board_id==board_id)

    total = post_query.count()
    posts = post_query.slice(start, end)
    pagination = Pagination(bs_version=3, page=page, total=total)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    context = {
        "boards": boards,
        "posts": posts,
        "pagination": pagination,
        "st": sort,
        "bd": board_id,
        "banners": banners
    }
    return render_template("front/index.html", **context)


@bp.get('/email/captcha')
def email_captcha():
    # /email/captcha?email=1482775872@qq.com
    email = request.args.get("email")
    if not email:
        return restful.params_error(message="请先传入邮箱！")

    source = list(string.digits)
    captcha = "".join(random.sample(source, 6))
    subject = "[OtakuFun]注册验证码"
    body = "[OtakuFun]您的注册验证码为：{}".format(captcha)
    current_app.celery.send_task("send_mail", (email, subject, body))
    cache.set(email, captcha)
    print(cache.get(email))
    # message返回一个html试试呢

    return restful.ok(message="邮件发送成功！")


@bp.route('/graph/captcha')
def graph_captcha():
    captcha, image = Captcha.gene_graph_captcha()
    key = md5((captcha + str(time.time())).encode('utf-8')).hexdigest()
    cache.set(key, captcha)  # 将验证码存在缓存中
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)  #
    resp = make_response(out.read())  # 文件指针指到最末尾了
    resp.content_type = "image/png"
    resp.set_cookie("_graph_captcha_key", key, max_age=3600)
    return resp


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            #生成图片，这样在注册是时就可以一起生成图像gavatar 的ident icon
            identicon = Identicon()
            #avatar需要一个text做名字，名字可以用唯一的邮箱来生成
            filenames = identicon.generate(text=md5(email.encode("utf-8")).hexdigest())
            avatar = filenames[2]
            user = UserModel(email=email, username=username, password=password, avatar=avatar)
            db.session.add(user)
            db.session.commit()
            return restful.ok()
        else:
            message = form.messages[0]
            return restful.params_error(message=message)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                return restful.params_error("邮箱或密码错误")
            if not user.check_password(password):
                return restful.params_error("邮箱或密码错误")
            session['user_id'] = user.id
            #如果是员工才生成token
            token = ""
            permissions=[]
            if user.is_staff:
                token = create_access_token(identity=user.id)
                for attr in dir(Permission):
                    if not attr.startswith("_"):
                        permission = getattr(Permission, attr)
                        if user.has_permission(permission):
                            permissions.append(attr.lower())


            if remember == 1:
                session.permanent = True
            user_dict = user.to_dict()
            user_dict['permissions'] = permissions
            return restful.ok(data={"token": token, "user": user_dict})
        else:
            return restful.params_error(message=form.messages[0])


@bp.route("/logout")
def logout():
    session.clear()
    return redirect('/')


@bp.route("/setting")
@login_required
def setting():
    email_hash = md5(g.user.email.encode("utf-8")).hexdigest()
    return render_template("front/setting.html", email_hash=email_hash)


@bp.post("/avatar/upload")
@login_required
def upload_avatar():
    form = UploadImageForm(request.files)
    if form.validate():
        image = form.image.data
        filename = image.filename
        # 获取后缀名，并且添加到md5
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email + str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['AVATARS_SAVE_PATH'], filename)
        image.save(image_path)
        g.user.avatar = filename
        db.session.commit()
        return restful.ok(data={"avatar": filename})
    else:
        message = form.messages[0]
        return restful.params_error(message=message)


@bp.post("/profile/edit")
@login_required
def edit_profile():
    form = EditProfileForm(request.form)
    if form.validate():
        signature = form.signature.data
        g.user.signature = signature
        db.session.commit()
        return restful.ok()
    else:
        return restful.params_error(message=form.messages[0])


@bp.route("/post/publish", methods=['GET', 'POST'])
@login_required
def post_publish():
    if request.method == 'GET':
        boards = BoardModel.query.order_by(BoardModel.priority.desc()).all()
        return render_template("/front/post_publish.html", boards=boards)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            try:
                board = BoardModel.query.get(board_id)
            except Exception as e:
                return restful.params_error(message="板块不存在！")
            post_model = PostModel(title=title, content=content, board=board, author=g.user)
            db.session.add(post_model)
            db.session.commit()
            return restful.ok(data={"id": post_model.id})
        else:
            return restful.params_error(message=form.messages[0])


@bp.post("/post/image/upload")
@login_required
def upload_post_image():
    form = UploadImageForm(request.files)
    if form.validate():
        image = form.image.data
        filename = image.filename
        # 获取后缀名，并且添加到md5
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email + str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['POST_IMAGE_SAVE_PATH'], filename)
        image.save(image_path)
        # db.session.commit()
        return jsonify({"errno": 0, "data": [{
            "url": url_for("media.get_post_image", filename=filename),
            "alt": filename,
            "href": ""
        }]})
    else:
        message = form.messages[0]
        return restful.params_error(message=message)


@bp.get("/post/detail/<int:post_id>")
def post_detail(post_id):
    try:
        post_model = PostModel.query.get(post_id)
    except:
        return "404"
    comment_count = CommentModel.query.filter_by(post_id=post_id).count()
    context = {
        "post": post_model,
        "comment_count": comment_count
    }
    return render_template("front/post_detail.html", **context)


#   return render_template("front/post_detail.html", post=post_model, comment_count=comment_count)

@bp.post("/comment")
@login_required
def public_comment():
    form = PublicCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        try:
            post_model = PostModel.query.get(post_id)
        except Exception as e:
            return restful.params_error(message="帖子不存在！")

blueprints/media/views.py
from flask import Blueprint, send_from_directory, current_app

bp = Blueprint("media", __name__, url_prefix="/media")
#/media/avatar/abc.jpg
#部署的时候，在nginx中配置一个/media前装的urL
# 访向/media的时候，我们指定让他从media文件夹下寻找文件

@bp.route("/avatar/<filename>")
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@bp.route("/post/<filename>")
def get_post_image(filename):
    return send_from_directory(current_app.config['POST_IMAGE_SAVE_PATH'], filename)


@bp.route("/banner/<filename>")
def get_banner_image(filename):
    return send_from_directory(current_app.config['BANNER_SAVE_PATH'], filename)

templates/front/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{csrf_token() }}">
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{url_for('static', filename= 'front/js/zlajax.js')}}"></script>
    <script src="{{url_for('static', filename= 'front/js/zlparam.js')}}"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='front/css/front_base.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">OtakuFun</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="请输入关键字">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                {{user.username}}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="{{url_for('front.cms')}}">后台管理</a></li>
                                <li><a href="{{url_for('front.setting')}}">设置</a></li>
                                <li><a href="{{url_for('front.logout')}}">注销</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{url_for('front.login')}}">登录</a></li>
                        <li><a href="{{url_for('front.register')}}">注册</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

templates/front/index.html
{% extends "front/base.html" %}

{% block title %}
OtakuFun
{% endblock %}


{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='/front/css/index.css')}}">
{% endblock %}

{% block body%}
<div class="lg-container">
    <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
        <!-- 指示器 -->
        <ol class="carousel-indicators">
            {% for banner in banners %}
            {% if loop.first %}
                <li data-target="#carousel-example-generic" data-slide-to="{{loop.index0}}" class="active"></li>
            {% else %}
                <li data-target="#carousel-example-generic" data-slide-to="{{loop.index0}}"></li>
            {% endif %}
            {% endfor %}
        </ol>
        <!-- 轮播图 -->
        <div class="carousel-inner" role="listbox">
            {% for banner in banners %}
                {% if loop.first %}
                    <div class="item active">
                {% else %}
                    <div class="item">
                {% endif %}
                    <a href="{{banner.link_url}}" target="_blank">
                        <img src="{{banner.image_url}}" alt="{{ banner.name }}">
                    </a>
            </div>
            {% endfor %}
        </div>

        <!-- 左右切换的控制按钮 -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="post-group">
        <ul class="post-group-head">
            {% if st==1 %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
                    <a href={{url_for("front.index", st=1, bd=bd )}}>最新</a>
                </li>

<!--            <li><a href="#">点赞最多</a></li>-->
            {% if st==2 %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
                    <a href={{url_for("front.index", st=2, bd=bd)}}>评论最多</a>
                </li>
        </ul>
        <ul class="post-list-group">
            {% for post in posts %}
            <li>
                <div class="author-avatar-group">
                    <img src="{{url_for('media.get_avatar', filename=post.author.avatar)}}" alt="">
                </div>
                <div class="post-info-group">
                    <p class="post-title">
                        <a href="{{ url_for('front.post_detail', post_id=post.id)}}">{{post.title}}</a>
                    </p>
                    <p class="post-info">
                        <span>作者：{{post.author.username}}</span>
                        <span>发表时间：{{post.create_time}}</span>
                        <span>评论:{{post.comments|length}}</span>
<!--                        <span>阅读:100</span>-->
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
        <div style="text-align:center;">
           {{pagination.links}}
        </div>
    </div>
</div>
<div class="sm-container">
    <div style="padding-bottom:10px;">
        <a href="{{ url_for('front.post_publish') }}" class="btn btn-warning btn-block">发布帖子</a>
    </div>
    <div class="list-group">
        {% if bd %}
            <a href="/" class="list-group-item">所有板块</a>
        {% else %}
            <a href="/" class="list-group-item active">所有板块</a>
        {% endif %}

        {% for board in boards %}
            {% if bd == board.id %}
                <a href="{{url_for('front.index', bd=board.id, page=1)}}" class="list-group-item active">
            {% else %}
                <a href="{{url_for('front.index', bd=board.id, page=1)}}" class="list-group-item">
            {% endif %}
                {{board.name}}
            </a>
        {% endfor %}
    </div>
</div>
{% endblock%}

templates/front/login.html
{% extends "front/base.html" %}

{% block title %}登录-OtakuFun {% endblock %}

{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='front/css/signbase.css')}}">
<script src="{{url_for('static', filename='front/js/login.js')}}"></script>
{% endblock %}

{% block body %}
<div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src="{{url_for('static', filename='front/images/logo.jpg')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                OtakuFun-login
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <input type="text" class="form-control" name="email" placeholder="邮箱">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="remember" value="1">记住我
                    </label>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
                </div>
                <div class="form-group">
                    <a href="#" class="signup-link">没有账号？立即注册</a>
                    <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
                </div>
            </div>
        </div>
{% endblock %}

templates/front/post_detail.html
{% extends "front/base.html" %}

{% block title %}
{{ post.title }} - Otakufun
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/highlight/styles/agate.min.css') }}">
<script src="{{ url_for('static', filename='lib/highlight/highlight.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='front/css/post_detail.css') }}">
<script src="{{ url_for('static', filename='front/js/post_detail.js') }}"></script>
{% endblock %}

{% block body %}
<div class="post-container">
    <h2>{{ post.title }}</h2>
    <p class="post-info-group">
        <span>发表时间：{{ post.create_time }}</span>
        <span>作者：{{ post.author.username }}</span>
        <span>所属板块：{{ post.board.name }}</span>
        <span>评论数：{{ comment_count }}</span>
    </p>
    <div class="post-content">
        {{ post.content|safe }}
        <!--  safe是为了防止html标签被转义      -->
    </div>
</div>
<div class="comment-group">
    <h3>评论列表</h3>
    <ul class="comment-list-group">
        {% for comment in post.comments %}
        <li>
            <div class="avatar-group">
                <img src="{{ url_for('media.get_avatar', filename=comment.author.avatar) }}" alt="">
            </div>
            <div class="comment-content">
                <p class="author-info">
                    <span>{{ comment.author.username }}</span>
                    <span>{{ comment.create_time }}</span>
                </p>
                <p class="comment-txt">
                    {{ comment.content }}
                </p>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="add-comment-group">
    <h3>发表评论</h3>
    <textarea name="comment" id="comment-textarea" style="width: 100%; resize:vertical;"></textarea>
    <div class="comment-btn-group">
        <button class="btn btn-primary" id="comment-btn" data-post-id="{{ post.id }}"
                data-user-id="{{ user.id if user else '' }}">发表评论
        </button>
    </div>
</div>
{% endblock %}

templates/front/post_publish.html
{% extends "front/base.html" %}

{% block title %}
发布帖子
{% endblock %}

{% block head %}
  <script src="{{ url_for('static', filename='lib/wangEditor/wangEditor.min.js') }}"></script>
  <script src="{{ url_for('static', filename='front/js/public_post.js') }}"></script>
{% endblock %}

{% block body %}
  <h1 style="text-align: center; padding: 20px;">发布帖子</h1>
    <form action="" method="post">
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon">标题</span>
          <input type="text" class="form-control" name="title">
        </div>
      </div>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon">板块</span>
          <select name="board_id" class="form-control">
            {% for board in boards %}
              <option value="{{ board.id }}">{{ board.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-group">
        <div id="editor"></div>
      </div>
      <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
      </div>
    </form>
{% endblock %}

templates/front/register.html
{% extends "front/base.html" %}

{% block title%}注册-OtakuFUn {% endblock %}

{% block head%}
<link rel="stylesheet" href="{{url_for('static', filename='front/css/signbase.css')}}">
<script src="{{url_for('static', filename='front/js/register.js')}}"></script>
{% endblock %}

{% block body%}
<div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src="{{url_for('static', filename='front/images/logo.jpg')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                OtakuFun-register
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <div class="input-group">
                        <input type="email" class="form-control" name="email" placeholder="邮箱">
                        <spanemail_captcha class="input-group-btn">
                            <button id="email-captcha-btn" class="btn btn-default">发送验证码</button>
                        </spanemail_captcha>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="email_captcha" placeholder="邮箱验证码">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="repeat_password" placeholder="确认密码">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
                        <span class="input-group-addon captcha-addon">
                            <img id="captcha-img" class="captcha-img" src="{{url_for('front.graph_captcha')}}" alt="">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
                </div>
            </div>
        </div>
{% endblock %}

templates/front/setting.html
{% extends "front/base.html" %}

{%block title%}
    个人设置
{% endblock %}
{%block head%}
<script src="{{url_for('static', filename='front/js/setting.js')}}"></script>
<script src="{{url_for('static', filename='front/css/index.css')}}"></script>
<style>
    body{
      background-color: #f3f3f3;
    }
    .setting-group {
      width: 800px;
      background-color: #ffffff;
      margin: 0 auto;
      padding: 50px;
    }
    #avatar-img{
      width: 140px;
      height: 140px;
    }
</style>

{% endblock %}

{%block body%}
<div class="setting-group">
      <h1>{{user.username}}设置</h1>
      <div style="height: 20px;"></div>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱：</label>
          <input type="email" class="form-control" value="{{user.email}}" readonly>
        </div>
        <div class="form-group">
          <label>头像：</label>
          <div class="input-group">
            <img src="{{url_for('media.get_avatar', filename=user.avatar)}}" alt="..." class="img-circle" id="avatar-img">
            <input type="file" id="avatar-input" accept="image/jpeg, image/png">
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">个性签名：</label>
          <input type="text" class="form-control" id="signature-input" value="{{user.signature or " "}}" >
        </div>
        <button type="submit" id="submit-btn" class="btn btn-primary">保存</button>
      </form>
</div>
{% endblock %}